# Bun configuration file for test runner
[test]
root = "."
preload = ["./tests/bun.test.config.ts"]
coverage = false

# Path aliases for the entire project (affects tests too)
[install]
# Registry configuration - removed conflicting scopes
