version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-line-t3-app
    ports:
      - "12914:12914"  # ใช้ PORT จาก .env.prod
    env_file:
      - .env.prod
    restart: unless-stopped
    # ถ้าต้องการให้ container เข้าถึงไฟล์ใน local (เช่น สำหรับ development)
    # volumes:
    #   - .:/app # Mount โค้ดปัจจุบันเข้าไปใน container
    #   - /app/node_modules # ป้องกันไม่ให้ local node_modules ทับใน container
    #   - /app/.next

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    container_name: bun-line-t3-cron
    env_file:
      - .env.prod
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started # รอให้ app service เริ่มทำงานก่อน (อาจปรับเป็น service_healthy ถ้ามี health check)
