import { type Metadata } from "next";
import { Prompt } from "next/font/google";
import Providers from "./providers";

import "@/styles/globals.css";
import "@/styles/ring.css";

// 🎨 กำหนด Google Font Prompt
const promptFont = Prompt({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-prompt",
});

// ใช้ static font class names เพื่อป้องกัน hydration mismatch
const FONT_CLASSES = `${promptFont.variable} font-prompt antialiased`;

export const metadata: Metadata = {
  title: "Bun LINE T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      id="html-root"
      lang="th"
      className={promptFont.variable}
      suppressHydrationWarning={true}
    >
      <body
        id="body-main"
        className={FONT_CLASSES}
        suppressHydrationWarning={true}
      >
        <Providers>
          <div id="modal-root"></div>
          <main id="main-content">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
