import { type Metadata } from "next";
import { Prompt } from "next/font/google";
import Providers from "./providers";

import "~/styles/globals.css";
import "~/styles/ring.css";

const prompt = Prompt({
  subsets: ["thai", "latin"],
  display: "swap",
  variable: "--font-prompt",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Bun LINE T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th" className={prompt.variable}>
      <head>
        <meta
          name="theme-color"
          media="(prefers-color-scheme: light)"
          content="#2e026d"
        />
        <meta
          name="theme-color"
          media="(prefers-color-scheme: dark)"
          content="#2e026d"
        />
      </head>
      <body className={prompt.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
