import { type Metadata } from "next";
import Providers from "./providers";

import "~/styles/globals.css";
import "~/styles/ring.css";

// ใช้ static font class names เพื่อป้องกัน hydration mismatch
const FONT_CLASSES = 'font-prompt antialiased'

export const metadata: Metadata = {
  title: "Bun LINE T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html 
      lang="th" 
      style={{ ['--font-prompt' as any]: 'Prompt, sans-serif' }}
      className="font-prompt"
    >
      <head>
        <meta
          name="theme-color"
          media="(prefers-color-scheme: light)"
          content="#2e026d"
        />
        <meta
          name="theme-color"
          media="(prefers-color-scheme: dark)"
          content="#2e026d"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <meta name="format-detection" content="telephone=no" />
        {/* Google Fonts - โหลดใน head เพื่อป้องกัน hydration mismatch */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link 
          href="https://fonts.googleapis.com/css2?family=Prompt:wght@300;400;500;600;700&display=swap" 
          rel="stylesheet" 
        />
        {/* Development checker - โหลดเฉพาะใน development */}
        {process.env.NODE_ENV === 'development' && (
          <>
            <script src="/dev-checker.js" defer />
            <script src="/production-redirect.js" defer />
          </>
        )}
      </head>
      {/* 
        🔧 suppressHydrationWarning: แก้ไข hydration mismatch จาก browser extensions
        Browser extensions (เช่น Grammarly, ColorZilla) อาจแทรก attributes เข้าไปใน body:
        - data-new-gr-c-s-check-loaded, data-gr-ext-installed (Grammarly)
        - cz-shortcut-listen (ColorZilla)
        - อื่นๆ
        การใช้ suppressHydrationWarning ที่ body element จะป้องกัน warning เหล่านี้
        โดยไม่กระทบต่อการทำงานของแอป
      */}
      <body 
        className={FONT_CLASSES} 
        suppressHydrationWarning={true}
      >
        <Providers>
          <div id="modal-root"></div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
